using DB_AngoraLib.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DB_AngoraLib.MockData
{
    public class MockRabbits
    {
        private static List<Rabbit> _rabbitsList = new List<Rabbit>()
        {

            //---------------------: IDAS RABBIT COLLECTION

            new Rabbit(
            "5095",                 // RightEarId
            "002",                  // LeftEarId
            "IdasId",               // OriginId (User UserOrigin)      
            "IdasId",               // OwnerId (User UserOwner)      
            "Sov",                  // NickName
            Race.Angora,
            Color.Blå,
            new DateOnly(2020, 06, 12), // Format: yyyy-MM-dd
            new DateOnly(2022, 07, 22), // Format: yyyy-MM-dd
            Gender.Hun,
            ForSale.Nej,
            null,                   // Father_EarCombId
            "5095-001"),            // Mother_EarCombId

            new Rabbit(
            "5095",
            "001",
            "IdasId",
            "IdasId",
            "Kaliba",
            Race.Angora,
            Color.Gråblå_LilleEgern,
            new DateOnly(2019, 02, 27),
            new DateOnly(2024, 04, 13),
            Gender.Hun,
            ForSale.Ja,
            null,
            null),

            new Rabbit(
            "5095",
            "003",
            "IdasId",
            "IdasId",
            "Smørklat Smør",
            Race.Angora,
            Color.Gulbrun_Isabella,
            new DateOnly(2020, 03, 12),
            new DateOnly(2023, 11, 3),
            Gender.Hun,
            ForSale.Nej,
            null,
            "5095-001"),

            new Rabbit(
            "4640",
            "120",
            null,
            "IdasId",
            "Mulan",
            Race.Angora,
            Color.Blå,
            new DateOnly(2021, 05, 11),
            new DateOnly(2023, 11, 3),
            Gender.Hun,
            ForSale.Nej,
            null,
            null),

            new Rabbit(
            "4640",
            "105",
            null,
            "IdasId",
            "Ingolf",
            Race.Angora,
            Color.Chinchilla,
            new DateOnly(2021, 04, 05),
            null,
            Gender.Han,
            ForSale.Ja,
            null,
            null),

            new Rabbit(
            "5095",
            "0124",
            "IdasId",
            "IdasId",
            "Aron",
            Race.Satin_Angora,
            Color.Kanel,
            new DateOnly(2024, 05, 07),
            null,
            Gender.Han,
            ForSale.Ja,
            "V23-023",
            "5053-0223"),

            new Rabbit(
            "5095",
            "0624",
            "IdasId",
            "IdasId",
            "Articuno",
            Race.Satin_Angora,
            Color.Vildtblå_PerleEgern,
            new DateOnly(2024, 05, 07),
            null,
            Gender.Hun,
            ForSale.Ja,
            "V23-023",
            "5053-0223"),

            new Rabbit(
            "5095",
            "0224",
            "IdasId",
            "IdasId",
            "Azelf",
            Race.Satin_Angora,
            Color.Vildtrød_Harefarvet,
            new DateOnly(2024, 05, 07),
            null,
            Gender.Hun,
            ForSale.Ja,
            "V23-023",
            "5053-0223"),

            new Rabbit(
            "5095",
            "0324",
            "IdasId",
            "IdasId",
            "Arcanine",
            Race.Satin_Angora,
            Color.Vildtrød_Harefarvet,
            new DateOnly(2024, 05, 07),
            null,
            Gender.Han,
            ForSale.Ja,
            "V23-023",
            "5053-0223"),

            //---------------------: MAJAS RABBIT COLLECTION
            new Rabbit(
            "4398",
            "3020",
            null,
            "MajasId",
            "Douglas",
            Race.Lille_Rex,
            Color.Gulbrun_Isabella,
            new DateOnly(2022, 07, 22),
            null,
            Gender.Han,
            ForSale.Ja,
            null,
            null),

            new Rabbit(
            "5053",
            "0223",
            "MajasId",
            "MajasId",
            "Chinchou",
            Race.Satin_Angora,
            Color.Blå,
            new DateOnly(2023, 05, 30),
            null,
            Gender.Hun,
            ForSale.Ja,
            "4977-206",
            "4977-213"),

            new Rabbit(
            "5053",
            "0723",
            "MajasId",
            "MajasId",
            "Sandshrew",
            Race.Satin_Angora,
            Color.Brun_Havana,
            new DateOnly(2023, 10, 15),
            null,
            Gender.Han,
            ForSale.Ja,
            "4977-206",
            "4977-315"),

            new Rabbit(
            "5053",
            "1023",
            "MajasId",
            "MajasId",
            "Marabou",
            Race.Satin_Angora,
            Color.Brun_Havana,
            new DateOnly(2023, 10, 15),
            null,
            Gender.Hun,
            ForSale.Nej,
            "4977-206",
            "4977-315"),

            new Rabbit(
            "M63",
            "2104",
            null,
            "MajasId",
            "Ortovi",
            Race.Satin_Angora,
            Color.Elfenben,
            new DateOnly(2023, 05, 22),
            null,
            Gender.Hun,
            ForSale.Ja,
            "M63-085",
            "M63-164"),

            new Rabbit(
            "5053",
            "0823",
            "MajasId",
            "MajasId",
            "Pepsi",
            Race.Satin_Angora,
            Color.Kanel,
            new DateOnly(2023, 10, 15),
            null,
            Gender.Hun,
            ForSale.Nej,
            "4977-206",
            "4977-315"),

            new Rabbit(
            "5053",
            "0923",
            "MajasId",
            "MajasId",
            "Cola",
            Race.Satin_Angora,
            Color.Rødbrun_Madagascar,
            new DateOnly(2023, 10, 15),
            null,
            Gender.Han,
            ForSale.Ja,
            "4977-206",
            "4977-315"),

            new Rabbit(
            "5053",
            "0623",
            "MajasId",
            "MajasId",
            "Karla",
            Race.Satin_Angora,
            Color.Gråblå_MarburgerEgern,
            new DateOnly(2023, 08, 17),
            null,
            Gender.Hun,
            ForSale.Nej,
            "4977-206",
            "4977-213"),

            new Rabbit(
            "M63",
            "3102",
            null,
            "MajasId",
            "Xådda",
            Race.Satin_Angora,
            Color.Gråblå_MarburgerEgern,
            new DateOnly(2023, 09, 23),
            null,
            Gender.Hun,
            ForSale.Nej,
            "M63-0204",
            "M63-0000"),

            new Rabbit(
            "4977",
            "206",
            null,
            "MajasId",
            "Dario",
            Race.Satin_Angora,
            Color.Sort_Alaska,
            new DateOnly(2022, 02, 02),
            new DateOnly(2024, 04, 05),
            Gender.Han,
            ForSale.Ja,
            "M63-044",
            "M63-989"),

            new Rabbit(
            "4977",
            "315",
            null,
            "MajasId",
            "Miranda",
            Race.Satin_Angora,
            Color.Sort_Alaska,
            new DateOnly(2023, 01, 13),
            new DateOnly(2024, 04, 15),
            Gender.Hun,
            ForSale.Nej,
            "4977-205",
            "13-232"),

            new Rabbit(
            "5053",
            "0423",
            "MajasId",
            "MajasId",
            "Gastly",
            Race.Satin_Angora,
            Color.Sort_Alaska,
            new DateOnly(2023, 05, 30),
            null,
            Gender.Hun,
            ForSale.Nej,
            "4977-206",
            "4977-213"),

            new Rabbit(
            "V23",
            "023",
            null,
            "MajasId",
            "Aslan",
            Race.Satin_Angora,
            Color.Vildtbrun,
            new DateOnly(2020, 04, 10),
            new DateOnly(2024, 04, 23),
            Gender.Han,
            ForSale.Ja,
            null,
            null),

            new Rabbit(
            "4977",
            "213",
            null,
            "MajasId",
            "Frida",
            Race.Satin_Angora,
            Color.Vildtrød_Harefarvet,
            new DateOnly(2022, 03, 24),
            null,
            Gender.Hun,
            ForSale.Ja,
            "M63-125",
            "M63-155"),

            new Rabbit(
            "5053",
            "0120",
            "MajasId",
            "MajasId",
            "Ulla",
            Race.Angora,
            Color.Gulbrun_Isabella,
            new DateOnly(2020, 03, 25),
            new DateOnly(2021, 05, 31),
            Gender.Hun,
            ForSale.Nej,
            null,
            null),

            new Rabbit(
            "3658",
            "0819",
            null,
            "MajasId",
            "Karina",
            Race.Angora,
            Color.Hvid_Albino,
            new DateOnly(2019, 05, 31),
            new DateOnly(2023, 01, 31),
            Gender.Hun,
            ForSale.Nej,
            null,
            null),

            new Rabbit(
            "5053",
            "0523",
            "MajasId",
            "MajasId",
            "Charizard",
            Race.Satin_Angora,
            Color.Vildtrød_Harefarvet,
            new DateOnly(2023, 08, 17),
            null,
            Gender.Han,
            ForSale.Ja,
            "4977-206",
            "4977-213"),

            new Rabbit(
            "5053",
            "0123",
            "MajasId",
            "MajasId",
            "Pichu",
            Race.Satin_Angora,
            Color.Vildtrød_Harefarvet,
            new DateOnly(2023, 05, 30),
            null,
            Gender.Hun,
            ForSale.Ja,
            "4977-206",
            "4977-213"),

            new Rabbit(
            "5053",
            "0323",
            "MajasId",
            "MajasId",
            "Hunter",
            Race.Satin_Angora,
            Color.Sort_Alaska,
            new DateOnly(2023, 08, 17),
            new DateOnly(2023, 12, 18),
            Gender.Han,
            ForSale.Nej,
            "4977-206",
            "4977-213"),

            new Rabbit(
            "5053",
            "0124",
            "MajasId",
            "MajasId",
            "Rollo Darminatan",
            Race.Satin_Angora,
            Color.Vildtrød_Harefarvet,
            new DateOnly(2024, 04, 1),
            null,
            Gender.Han,
            ForSale.Nej,
            "V23-023",
            "5053-0423"),

            new Rabbit(
            "5053",
            "0224",
            "MajasId",
            "MajasId",
            "Chokolade",
            Race.Satin_Angora,
            Color.Gråblå_LilleEgern,
            new DateOnly(2024, 04, 18),
            null,
            Gender.Hun,
            ForSale.Nej,
            "5053-0723",
            "M63-3102"),

            new Rabbit(
            "5053",
            "0324",
            "MajasId",
            "MajasId",
            "Beartic",
            Race.Satin_Angora,
            Color.Gråblå_LilleEgern,
            new DateOnly(2024, 04, 18),
            null,
            Gender.Han,
            ForSale.Nej,
            "5053-0723",
            "M63-3102"),

            new Rabbit(
            "5053",
            "0524",
            "MajasId",
            "MajasId",
            "Metchi",
            Race.Satin_Angora,
            Color.Brun_Havana,
            new DateOnly(2024, 04, 18),
            null,
            Gender.Han,
            ForSale.Nej,
            "5053-0723",
            "M63-3102"),

            new Rabbit(
            "5053",
            "0724",
            "MajasId",
            "MajasId",
            "Dewgong",
            Race.Satin_Angora,
            Color.Gråblå_MarburgerEgern,
            new DateOnly(2024, 04, 18),
            null,
            Gender.Han,
            ForSale.Nej,
            "5053-0723",
            "M63-3102"),

            new Rabbit(
            "5053",
            "10724",
            "MajasId",
            "MajasId",
            "Ice Beam",
            Race.Satin_Angora,
            Color.Gråblå_LilleEgern,
            new DateOnly(2024, 04, 18),
            null,
            Gender.Hun,
            ForSale.Nej,
            "5053-0723",
            "M63-3102"),

        };

        public static List<Rabbit> GetMockRabbits()
        { return _rabbitsList; }

    }
}
